on:
  push:
    branches:
      - main

name: Continuous Integration

jobs:
  quickcheck:
    name: "Get the version from Cargo.toml"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo check
      - run: cargo pkgid
      - run: 'echo "$(cargo pkgid | cut -d# -f2)"'
      - id: rustversion
        run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'
  build:
    name: Compiling rust binary
    runs-on: ubuntu-latest
    needs: [ quickcheck ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - run: cargo install cargo-deb
      - run: cargo deb

      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/

  release:
    name: "Release Version ${{needs.quickcheck.outputs.version}}"
    runs-on: ubuntu-latest
    needs: [ build, quickcheck ]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/papierkram"
          tag: "v${{needs.quickcheck.outputs.version}}"

  ppa:
    name: "Creates a PPA in Github Pages"
    runs-on: ubuntu-latest
    needs: [ build, quickcheck ]
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - run: bash build-ppa.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/gh-pages/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2