on:
  push:
    branches:
      - main

name: Continuous Integration

jobs:
  quickcheck:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo check
      - run: cargo pkgid
      - run: 'echo "$(cargo pkgid | cut -d# -f2)"'
      - id: rustversion
        run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'
  build:
    name: Compiling rust binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions/upload-artifact@v3
        with:
          name: Executable
          path: target/release/papierkram

  release:
    name: "Release Version ${{needs.quickcheck.outputs.version}}"
    runs-on: ubuntu-latest
    needs: [ build, quickcheck ]
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/papierkram"
          tag: "v${{needs.quickcheck.outputs.version}}"
