on:
  push:
    branches:
      - main

name: Continuous Integration

jobs:
  build:
    name: Compiling rust binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: mkdir target || true
      - run: echo "$(cargo pkgid | cut -d# -f2)" > target/version
      - run: cargo clean
      - run: cargo build --release --all-features
      - run: cargo install cargo-deb
      - run: cargo deb

      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/

  release:
    name: "Release Version"
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: echo "version=$(cat target/version)" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/papierkram,target/debian/*.deb"
          tag: "v${{ env.version }}"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/papierkram,target/debian/*.deb"
          tag: "latest"

  ppa:
    name: "Creates a PPA in Github Pages"
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: echo "${{ secrets.PPA_SIGNING_KEY }}" > ppa_signing_key.gpg
      - run: gpg --import ppa_signing_key.gpg
      - run: bash build-ppa.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/gh-pages/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2